### ISSUE TITLE
Deepsight Resonance weapons?

### ISSUE THREAD

**Issue by mturquette** [TMMania/Vault-Analyzer#17]
Do the search filters currently take into account red outline weapons that haven't been completed yet?

**Comment by TMMania** [comment]
The Vault Analyzer doesn't do much with weapons. The only delete conditions for weapons is if the weapon is sunset or marked junk.

**Comment by HVCFOGEY34** [comment]
It would be cool if it did more.

**Comment by TMMania** [comment]
Automating weapon management is a waaaay bigger headache than automating armor management and everyone has their own opinions about what weapons they like, so there really isn't much that could be added besides some kind of filter that highlights weapons that are on a trashlist and have their Deepsight completed, but the trashlists aren't well maintained because weapon curation is a massive headache.

Overall there isn't much to be done and you can just mark your deepsight weapons as trash once you're done with them and the VA will clean them up.

**Comment by HVCFOGEY34** [comment]
Fair enough. Thanks for the explanation. I've been using Light.gg to find good weapon rolls and was wondering if there was a way to integrate with that, but don't know how that would work.

**Comment by mturquette** [comment]
Fogey you might try Destiny Item Manager which had a mechanism to find good
weapon rolls and highlight them. It comes with sane details (panda
paxxys/mercules list), but anyone can upload their curated list using a
specific format.

**Comment by HVCFOGEY34** [comment]
I am. It's not updated for witch queen yet and I find that light.gg conflicts with it sometimes anyways. I figured its better to rely on light.gg anyways.

**Comment by TMMania** [comment]
Just closing this, seems like the initial question was answered.
